language: php

php:
  - 5.3
  - 5.4

before_script:
  - mkdir ../libraries
  - git clone --branch=master --depth=100 --quiet git://github.com/UnionOfRAD/lithium.git ../libraries/lithium

script: ../libraries/lithium/console/li3 test --filters=Profiler tests/cases